---

# Note: Try and limit these to packages that are distro-specific, and
# place commonly-named ones below.
- name: Install distro-specific prerequisites
  ansible.builtin.include_tasks: "{{ ansible_distribution|lower }}.yml"

- name: Install common support packages
  ansible.builtin.package:
    name:
      - jq
      - tar
      - curl
      - unzip
      - fontconfig

- name: Create product group
  ansible.builtin.group:
    name: "{{ atl_product_user }}"
    gid: "{{ atl_product_user_uid }}"

- name: Create product user
  ansible.builtin.user:
    name: "{{ atl_product_user }}"
    uid: "{{ atl_product_user_uid }}"
    group: "{{ atl_product_user }}"
    comment: "Product runtime user"

- name: Stop systemd-cleanup deleting the jvm socket file
  ansible.builtin.copy:
    src: java.conf
    dest: "/usr/lib/tmpfiles.d/java.conf"
    owner: root
    group: root
    mode: "644"
  register: systemd_config_changed

- name: Force systemd to reload daemon configuration
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - systemd_config_changed is defined
    - molecule_yml is not defined  # molecule cannot run systemctl commands and notest doesn't work for handlers
