---
collections:
  - name: amazon.aws
    version: "4.1.0"
  - name: ansible.posix
    version: "1.4.0"
  - name: community.docker
    version: "3.0.2"
  - name: community.general
    version: "5.5.0"
  - name: community.postgresql
    version: "2.2.0"
