---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "jira"
    atl_product_edition: "jira-software"
    atl_product_user: "jira"
    # Version 8.14.0 is chosen deliberately as it is a version where jira and jira-software returns different buildNumber from MPAC
    # See DCD-1216 for context
    atl_product_version: "8.14.0" 
    atl_install_jsd_as_obr: true
    atl_systemd_service_name: "jira.service"
    atl_jdbc_encoding: 'UNICODE'
    atl_jdbc_collation: 'C'
    atl_jdbc_ctype: 'C'
    atl_jdbc_template: 'template0'
  pre_tasks:
    - name: Create cache dir
      ansible.builtin.file:
        path: '/media/atl/jira/shared/'
        state: directory
    - name: Seed version
      ansible.builtin.copy:
        dest: '/media/atl/jira/shared/jira-core.version'
        content: "8.14.0"
        force: false  # For idempotency check
  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
