---

- name: "Install systemd service file"
  ansible.builtin.template:
    src: "product.service.j2"
    dest: "{{ atl_systemd_service_dir }}/{{ atl_systemd_service_name }}"
    owner: root
    group: root
    mode: 0640
  notify:
    - Enable Product
    - Restart Product
