---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "confluence"
    atl_product_edition: "confluence"
    atl_product_user: "confluence"
    atl_product_version: "7.20.0-CONFSERVER-63193-m01"
  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
