---
- name: Converge
  hosts: all
  vars:
    atl_product_user: "jira"
    atl_product_family: "jira"
    atl_product_edition: "jira-software"
    atl_startup_enable: false

    ansible_vars_dump_location: "/tmp/ansible-vars.yml"

  tasks:
    - ansible.builtin.include_vars: ../../defaults/main.yml

    # workaround Molecule idempotence check
    # normal pattern of setting changed_when allows file to be written twice, which takes extra time
    - name: Check if vars have already been dumped
      ansible.builtin.stat:
        path: "{{ ansible_vars_dump_location }}"
      register: ansible_vars_stat_result

    - name: Dump vars to file for inspection
      ansible.builtin.copy:
        content: |
          {{ vars | to_nice_yaml }}
        dest: "{{ ansible_vars_dump_location }}"
      when: not ansible_vars_stat_result.stat.exists
