---
- name: Converge
  hosts: all
  vars:
    atl_product_user: "testuser"
    atl_product_home: "/data/atlassian/product"
    atl_product_installation_base: "/data/atlassian/product/install"
    atl_installer_temp: "/data/atlassian/temp"
    atl_product_home_shared: "/media/sharedjirajira/shared"
    atl_product_shared_plugins: "/media/sharedjirajira/plugins/"
  roles:
    - role: linux_common
    - role: product_common
