---

- name: Fetch the latest version from URL
  ansible.builtin.set_fact:
    atl_product_version_json: "{{ lookup('url', 'https://marketplace.atlassian.com/rest/2/products/key/jira-servicedesk/versions') }}"

- name: Set the local var to retrieved version
  ansible.builtin.set_fact:
    atl_latest_version: "{{ atl_product_version_json._embedded.versions[0].name }}"